[package]
name = "rust-crypto"
version = "0.1.0"
authors = ["alex <kooparse@protonmail.com>"]

[dependencies]
term = "0.4.6"
prettytable-rs = "0.6"
reqwest = "0.8.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
clap = {version = "2.29", features = ["yaml"]}
